- Updated buildscript with new -s|--stable version.  This will show a menu with a list of all available stable git tags of OpenWRT. The script will then build that rather than the latest git. - Updated .config files for compatiablilty with OpenWRT v21 - Updated config files to support plugging a printer or thumb drive into the USB 3.0 socket and the most common file system are now supported - Updated config files to better support fast roaming, and 80211v,k and r - Added umdns and config, a new requirement of DAWN - Updated config files to allow sending of files over the uart serial connection if required - Added a file with instructions on how to debrick the router easily, and possible ways of sending files over uart serial connections (in LibreOffice Write odt format) - probably other stuff I've forgotten

diff --git a/xrp3-build-script b/xrp3-build-script
--- a/xrp3-build-script
+++ b/xrp3-build-script
@@ -1,25 +1,30 @@
 #!/usr/bin/env bash
 
+#Changelog
+#1.0 initial version
+#1.1 added option to checkout a stable version of openwrt
+
 . "${PWD}/commonfunctions"
 
 declare -r PROG_NAME="xpr3-build-script"
-declare -r PROG_VER="1.0"
+declare -r PROG_VER="1.1"
 declare -r AUTHOR="Alex Wood"
 declare -r AUTHOR_EMAIL="alex@alex-wood.org.uk"
 
 # Created by argbash-init v2.8.1
 # ARG_OPTIONAL_BOOLEAN([clean],[c],[Cleans old build files before building to make sure old files don't halt the build process.  As a result build time is substantially long (the toolchain, linux, utils, everything is rebuilt],[on])
 # ARG_OPTIONAL_BOOLEAN([renew_config],[r],[Replace any current configuration (.config) with the default one.  WARNING: This will undo any changes you have made using make menuconfig.],[on])
+# ARG_OPTIONAL_BOOLEAN([stable],[s],[Shows a menu allowing you to choose a STABLE version of OpenWRT to use (i.e. not the bleeding edge, and possibly not working, latest git version.  WARNING: This will have to turn on clean and update.],[off])
 # ARG_OPTIONAL_BOOLEAN([update],[u],[Update the git repo (for OpenWRT and DAWN) and update and install the feeds.  Nano is also repatched and DAWN is relinked.  WARNING: As this bring the code up to date with the 'bleeding 'edge' of OpenWRT some builds may fail until a fix has been commited to the OpenWRT/Feeds/DAWN repos],[on])
 # ARGBASH_SET_DELIM([ =])
 # ARG_OPTION_STACKING([getopt])
 # ARG_RESTRICT_VALUES([no-local-options])
-# ARG_HELP([Compiles a OpenWRT Snapshop image (i.e. using latest code from git) suitable suitable for a Xiaomi Mi Router 3 Pro being used in Wireless Access Point mode only.  Change *.config files to change router type; Change 99_uci_defaults, mac_hostnames and secrets in files to change how it is configured])
+# ARG_HELP([Compiles a OpenWRT Snapshop image (i.e. using latest code from git) suitable for a Xiaomi Mi Router 3 Pro being used in Wireless Access Point mode only.  Change *.config files to change router type; Change 99_uci_defaults, mac_hostnames and secrets in files to change how it is configured.])
 # ARG_VERSION([echo "${PROG_NAME} v${PROG_VER} by ${AUTHOR} (${AUTHOR_EMAIL})"])
 # ARGBASH_SET_INDENT([    ])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
@@ -35,13 +40,13 @@ die()
 
 evaluate_strictness()
 {
-    [[ "$2" =~ ^-(-(clean|renew_config|update|help|version)$|[cruhv]) ]] && die "You have passed '$2' as a value of argument '$1', which makes it look like that you have omitted the actual value, since '$2' is an option accepted by this script. This is considered a fatal error."
+    [[ "$2" =~ ^-(-(clean|renew_config|stable|update|help|version)$|[crsuhv]) ]] && die "You have passed '$2' as a value of argument '$1', which makes it look like that you have omitted the actual value, since '$2' is an option accepted by this script. This is considered a fatal error."
 }
 
 
 begins_with_short_option()
 {
-    local first_option all_short_options='cruhv'
+    local first_option all_short_options='crsuhv'
     first_option="${1:0:1}"
     test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -49,15 +54,17 @@ begins_with_short_option()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_clean="on"
 _arg_renew_config="on"
+_arg_stable="off"
 _arg_update="on"
 
 
 print_help()
 {
-    printf '%s\n' "Compiles a OpenWRT Snapshop image (i.e. using latest code from git) suitable suitable for a Xiaomi Mi Router 3 Pro being used in Wireless Access Point mode only.  Change *.config files to change router type; Change 99_uci_defaults, mac_hostnames and secrets in files to change how it is configured"
-    printf 'Usage: %s [-c|--(no-)clean] [-r|--(no-)renew_config] [-u|--(no-)update] [-h|--help] [-v|--version]\n' "$0"
+    printf '%s\n' "Compiles a OpenWRT Snapshop image (i.e. using latest code from git) suitable for a Xiaomi Mi Router 3 Pro being used in Wireless Access Point mode only.  Change *.config files to change router type; Change 99_uci_defaults, mac_hostnames and secrets in files to change how it is configured."
+    printf 'Usage: %s [-c|--(no-)clean] [-r|--(no-)renew_config] [-s|--(no-)stable] [-u|--(no-)update] [-h|--help] [-v|--version]\n' "$0"
     printf '\t%s\n' "-c, --clean, --no-clean: Cleans old build files before building to make sure old files don't halt the build process.  As a result build time is substantially long (the toolchain, linux, utils, everything is rebuilt (on by default)"
     printf '\t%s\n' "-r, --renew_config, --no-renew_config: Replace any current configuration (.config) with the default one.  WARNING: This will undo any changes you have made using make menuconfig. (on by default)"
+    printf '\t%s\n' "-s, --stable, --no-stable: Shows a menu allowing you to choose a STABLE version of OpenWRT to use (i.e. not the bleeding edge, and possibly not working, latest git version.  WARNING: This will have to turn on clean and update. (off by default)"
     printf '\t%s\n' "-u, --update, --no-update: Update the git repo (for OpenWRT and DAWN) and update and install the feeds.  Nano is also repatched and DAWN is relinked.  WARNING: As this bring the code up to date with the 'bleeding 'edge' of OpenWRT some builds may fail until a fix has been commited to the OpenWRT/Feeds/DAWN repos (on by default)"
     printf '\t%s\n' "-h, --help: Prints help"
     printf '\t%s\n' "-v, --version: Prints version"
@@ -92,6 +99,18 @@ parse_commandline()
                 if test -n "$_next" -a "$_next" != "$_key"
                 then
                     { begins_with_short_option "$_next" && shift && set -- "-r" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+                fi
+                ;;
+            -s|--no-stable|--stable)
+                _arg_stable="on"
+                test "${1:0:5}" = "--no-" && _arg_stable="off"
+                ;;
+            -s*)
+                _arg_stable="on"
+                _next="${_key##-s}"
+                if test -n "$_next" -a "$_next" != "$_key"
+                then
+                    { begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
                 fi
                 ;;
             -u|--no-update|--update)
@@ -137,6 +156,56 @@ parse_commandline "$@"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
+function get_tag()
+{
+    infoText "Generating OpenWRT Versions Menu" ${INFO_TEXT_MISC}
+#    local tagList=`git ls-remote --tags --quiet | grep -v "\^{}$" | grep -v "reboot" | cut -f 2 | cut -d '/' -f3 | sed 's/^v//g'`
+    local tagList=$(git for-each-ref --format="%(refname:short) %(creatordate:short)" "refs/tags/*" | grep -v "reboot" | sed 's/^v//g')
+    local i=0
+    local menu_data=""
+
+    #number each of the menu items
+    #Actually no, normally you would add a description to each menu item, but we can;t so just leave blank
+    #this also makes it easier when getting the chosen value from the menu later
+    #Well actually, the date of the tag is handy to know, so use that as the description
+    for tag in ${tagList}
+    do
+#        ((i++))
+#        menu_data+=${i}
+#        menu_data+=" "
+        menu_data+=${tag}
+        menu_data+=" "
+    done
+
+    #get the size of the screen
+    eval `resize`
+    #display menu, and redirect stderr to stdout, so we can store the chosen value in the variable menu_item_chosen
+    menu_item_chosen=$(whiptail --nocancel --title "Select OpenWRT Version to Compile" --menu "Choose the version you want to compile" \
+        ${LINES} ${COLUMNS} $((${LINES}-8)) ${menu_data} 3>&1 1>&2 2>&3)
+    if [ -z ${menu_item_chosen} ]
+    then
+        echo -e "ERROR: No tag selected..."
+        return
+    fi
+
+    #Normally you would need this to lookup the item chosen (as you are just given the tag_, but we are using the tag as name (no decription)
+#    let i=0
+#    for tag in ${menu_data}
+#    do
+#        ((i++))
+#        #we look at every second value, as one is the value and ther other is empty
+#        if (( ${i} == $((${menu_item_chosen}*2)) ))
+#        then
+#            menu_item_chosen=${tag}
+#            break;break
+#        fi
+#    done
+    local advice=$(git config --get advice.detachedHead 3>&1 1>&2 2>&3)
+    git config advice.detachedHead false
+    git checkout "refs/tags/v${menu_item_chosen}"
+    git config advice.detachedHead ${advice}
+}
+
 infoText "MAIN CODE START [${PROG_NAME} v${PROG_VER} by ${AUTHOR} (${AUTHOR_EMAIL})]" ${INFO_TEXT_MISC_NO_DOTS}
 GIT_ROOT="${HOME}/git"
 OPENWRT_ROOT="${GIT_ROOT}/openwrt"
@@ -144,12 +213,23 @@ DAWN_ROOT="${GIT_ROOT}/DAWN"
 DAWN_FEED_LINK="${OPENWRT_ROOT}/feeds/packages/net/dawn/git-src"
 CONFIG_DIRECTORY="${PWD}"
 
+if [[ "${_arg_stable}" = "on" && ( "${_arg_update}" = "off" || "${_arg_clean}" = "off" ) ]]
+then
+    msg="If you wish to build a STABLE version of OpenWRT, you must NOT set either --no-clean or --no-update"
+    errorText "${msg}"
+    die "${msg}" 1
+fi
+
 pushd "${OPENWRT_ROOT}"
 
 infoText "Build System Prerequisites/Dependancies" ${INFO_TEXT_INSTALL}
 sudo apt install -y subversion g++ zlib1g-dev build-essential git python python3 python3-distutils libncurses5-dev gawk gettext unzip file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath intltool util-linux asciidoc binutils
 
-if [ "${_arg_update}" = "on" ]
+if [ "${_arg_stable}" = "on" ]
+then
+    infoText "Setting OpenWRT Version" ${INFO_TEXT_MISC}
+    get_tag
+elif [ "${_arg_update}" = "on" ]
 then
     infoText "Updating from remote Git Repo" ${INFO_TEXT_MISC}
     git pull
@@ -229,5 +309,7 @@ else
     warnText "The image failed to compile, view the warnings above, or cd to ["${OPENWRT_ROOT}"] and run make -j1 V=s"
 fi
 popd
+
+#git ls-remote --tags --quiet | grep -v "\^{}$" | grep -v "reboot" | cut -f 2 | cut -d '/' -f3 | sed 's/^v//g' | sed ':a;N;$!ba;s/\n/\" \"\" \"/g' | sed 's/^/\"/' | sed 's/$/\"/' | whiptail --title "Choose a version to compile:" --menu "Choose a OpenWRT Version:" 25 78 16 70
 
 # ] <-- needed because of Argbash
